-- Paste this into the Supabase SQL Editor and click RUN

-- 1. Create Custom Profiles Table
-- (Supabase has a built-in auth.users table, but we need a public profile to store role and balance)
CREATE TABLE public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  name text not null,
  role text default 'user' not null,
  credit_limit numeric default 5000 not null,
  balance numeric default 0 not null
);

-- 2. Create Plans Table
CREATE TABLE public.plans (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  total numeric not null,
  items jsonb not null,
  status text default 'pending' not null,
  date text not null
);

-- 3. Create Catalog Table
CREATE TABLE public.catalog (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  image text not null
);

-- 4. Insert Initial Catalog Data
INSERT INTO public.catalog (name, price, image) VALUES
  ('Jasmine Rice 5kg', 250, '🍚'),
  ('Cooking Oil 1L', 90, '🛢️'),
  ('Canned Sardines', 25, '🥫'),
  ('Evaporated Milk', 35, '🥛'),
  ('Instant Noodles (6pk)', 75, '🍜'),
  ('White Sugar 1kg', 65, '🍬');

-- 5. Trigger to automatically create a profile when a new user signs up
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'name', 'user');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- TURN OFF RLS for now so we don't block any API requests during initial testing
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog DISABLE ROW LEVEL SECURITY;
